---
name: Build Browser Extension

on:
  pull_request:
    paths:
      - '*'
      - '!*.md'
      - '!*.txt'
  push:
    branches:
      - 'master'
    paths:
      - '*'
      - '!*.md'
      - '!*.txt'
      - '.github/workflows/build.yml'
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.0

      - name: Set up Node
        uses: actions/setup-node@v3.3.0
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          node-version: '16'

      - name: Npm install 
        run: |
          npm install

      - name: Print environment
        run: |
          node --version
          npm --version

      - name: Build
        run: npm run dist

      - name: Build Manifest v3
        run: npm run dist:mv3

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Chrome artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-chrome.zip
          asset_name: dist-chrome-${{ github.sha }}.zip
          asset_content_type: application/gzip

      - name: Upload Chrome MV3 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-chrome-MV3.zip
          asset_name: dist-chrome-MV3-${{ github.sha }}.zip
          asset_content_type: application/gzip

      - name: Upload Firefox artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-firefox.zip
          asset_name: dist-firefox-${{ github.sha }}.zip
          asset_content_type: application/gzip

      - name: Upload Firefox MV3 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-firefox-MV3.zip
          asset_name: dist-firefox-MV3-${{ github.sha }}.zip
          asset_content_type: application/gzip
